In [2]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

C:\Users\Chethana\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

# Load the dataset
(train_images, train_labels), (test_images, test_labels) = datasets.fashion_mnist.load_data()

# Normalize the pixel values
train_images = train_images / 255.0
test_images = test_images / 255.0


In [4]:
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


C:\Users\Chethana\anaconda3\lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
model.fit(train_images, train_labels, epochs=30, validation_data=(test_images, test_labels))


Epoch 1/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - accuracy: 0.7607 - loss: 0.6824 - val_accuracy: 0.8442 - val_loss: 0.4347
Epoch 2/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8534 - loss: 0.4037 - val_accuracy: 0.8534 - val_loss: 0.4152
Epoch 3/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8672 - loss: 0.3644 - val_accuracy: 0.8566 - val_loss: 0.3837
Epoch 4/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8722 - loss: 0.3499 - val_accuracy: 0.8680 - val_loss: 0.3618
Epoch 5/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8790 - loss: 0.3313 - val_accuracy: 0.8689 - val_loss: 0.3619
Epoch 6/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8822 - loss: 0.3204 - val_accuracy: 0.8764 - val_loss: 0.3463
Epoch 7/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8848 - loss: 0.3148 - val_accuracy: 0.8761 - val_loss: 0.3552
Epoch 8/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8862 - loss: 0.30

In [6]:
test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
print(f'Test accuracy: {test_acc}')
print('Test loss: ', test_loss)

313/313 - 1s - 3ms/step - accuracy: 0.8903 - loss: 0.3453
Test accuracy: 0.8902999758720398
Test loss:  0.34534770250320435


In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

# Filter for binary classes
binary_train_indices = np.where((train_labels == 0) | (train_labels == 1))
binary_test_indices = np.where((test_labels == 0) | (test_labels == 1))

binary_train_images = train_images[binary_train_indices]
binary_train_labels = train_labels[binary_train_indices]
binary_test_images = test_images[binary_test_indices]
binary_test_labels = test_labels[binary_test_indices]

# Flatten the images
binary_train_images = binary_train_images.reshape((binary_train_images.shape[0], 28*28))
binary_test_images = binary_test_images.reshape((binary_test_images.shape[0], 28*28))


In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# List of distance measures
distance_measures = ['euclidean', 'manhattan', 'hamming', 'minkowski']

for measure in distance_measures:
    knn = KNeighborsClassifier(n_neighbors=5,metric=measure)
    knn.fit(binary_train_images, binary_train_labels)
    predictions = knn.predict(binary_test_images)

    accuracy = accuracy_score(binary_test_labels, predictions)
    print(f'{measure.capitalize()} distance measure:')
    print(f'Accuracy: {accuracy}')
    print('Confusion Matrix:')
    print(confusion_matrix(binary_test_labels, predictions))
    print('Classification Report:')
    print(classification_report(binary_test_labels, predictions))
    print('-' * 40)


C:\Users\Chethana\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Euclidean distance measure:
Accuracy: 0.9875
Confusion Matrix:
[[994   6]
 [ 19 981]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1000
           1       0.99      0.98      0.99      1000

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000

----------------------------------------


C:\Users\Chethana\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Manhattan distance measure:
Accuracy: 0.9875
Confusion Matrix:
[[993   7]
 [ 18 982]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1000
           1       0.99      0.98      0.99      1000

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000

----------------------------------------


C:\Users\Chethana\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Hamming distance measure:
Accuracy: 0.8045
Confusion Matrix:
[[612 388]
 [  3 997]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.61      0.76      1000
           1       0.72      1.00      0.84      1000

    accuracy                           0.80      2000
   macro avg       0.86      0.80      0.80      2000
weighted avg       0.86      0.80      0.80      2000

----------------------------------------
Minkowski distance measure:
Accuracy: 0.9875
Confusion Matrix:
[[994   6]
 [ 19 981]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1000
           1       0.99      0.98      0.99      1000

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000

----------------------------------------


C:\Users\Chethana\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
